services:
  - type: web
    name: gate-ai
    env: python
    buildCommand: pip install --upgrade pip && pip install -r modified_requirements.txt
    startCommand: gunicorn -c gunicorn_config.py deploy:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false 